name: runtime_native_semaphores
homepage: https://pieces.app
repository: https://github.com/open-runtime/native_semaphores
version: 1.0.0-beta.7
description: A library for creating and managing named semaphores in Dart using FFI across macOS, Linux, and Windows.
environment:
  sdk: ^3.9.0
# Explicitly declare that this package works on all desktop platforms.
platforms:
  linux:
  macos:
  windows:
dependencies:
  # ==========================================================================
  #
  # Direct pub.dev dependencies
  #
  # ==========================================================================
  ffi: ^2.1.2
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.5
  safe_int_id: ^1.1.1
  runtime_common_codestyle:
    git:
      url: https://github.com/open-runtime/runtime_common_codestyle
      tag_pattern: v{{version}}
    version: ^0.1.5
